### ISSUE TITLE
Unable to verify IModel Error

### ISSUE THREAD

**Issue by venkateshpenchala** [imodeljs/imodel-query-agent#1]
I have recently registered for a project and iModel. I got all the details (Client ID, secret, project, and iModel). When I put these values in the seed project (imodel-query-agent), I get an error saying " Unable to verify IModel:'imodel-name', for project 'sample-project' exists in the iModel Hub: Failed to discover URL for service identified by "Mobile.ImsStsAuth". How do I resolve this?

![pastedimage](https://user-images.githubusercontent.com/15332516/50337123-75792500-0510-11e9-8044-1704bf9a015f.png)

**Comment by ramanujam-raman-zz** [comment]
Does this issue persist in successive runs? Do you have any network issues? The error log seems to indicate that the query below to the Url Discovery Service fails in your case:
https://buddi.bentley.com/WebService/GetUrl/?url=Mobile.ImsStsAuth&region=0

This is probably one of the first network requests made. You could consider using an utility like  [POSTMAN](https://www.getpostman.com/) to independently check if that query fails.

**Comment by venkateshpenchala** [comment]
Hi,

The issue does persist on successive runs and I tried it on Postman, the query fails on that too.
I don't have any such network issues encountered till now.

**Comment by ramanujam-raman-zz** [comment]
What error did you get with Postman? Can you paste the response you get? 

Also, does clicking the above link work for you? That would execute the query in the browser.

**Comment by venkateshpenchala** [comment]
![image](https://user-images.githubusercontent.com/15332516/50821352-4693e900-132f-11e9-886e-65d143c8be4a.png)

The Query gives the above output in the browser and postman. Yesterday for a while, it did not work in postman and now I get the above output. But I still get the same error on 'npm start' ("Unable to verify IModel:'imodel-name', for...")

**Comment by ramanujam-raman-zz** [comment]
Just to confirm - 
* you still get the entire error - i.e., "Failed to discover URL for service identified by Mobile.ImsStsAuth"
* and when you try the above query with POSTMAN it works

Can you run these tests around the same time? 

Any error that POSTMAN reports could be useful to diagnose this.

**Comment by venkateshpenchala** [comment]
I ran the tests at the same time and it is still the same. Works with Postman, and fails on 'npm start'

**Comment by ramanujam-raman-zz** [comment]
... and is the log exactly the same as what you reported before? i.e., you get the specific error
`"Failed to discover URL for service identified by Mobile.ImsStsAuth"`

If that's still the case, we would need to dig deeper to determine what's going wrong. We can perhaps add more logging to help with this, but in the current release, try the following debug procedure to determine why the HTTP call fails in your case.

Set a debug break point in the catch block below and examine the error you get:
`imodel-query-agent\node_modules\@bentley\imodeljs-clients\lib\Request.js:Line 255`
```javascript
    .catch(async (error) => {
        const parsedError = errorCallback(error);
        return Promise.reject(parsedError);
    });
```

Note that, if you are using visual studio code, you need to modify the settings.json to view the javascript file (change the exclude flags in the settings below to "false"):
`imodel-query-agent\.vscode\settings.json`

```javascript
    "files.exclude": {
    "**/node_modules": false,
    "**/lib": false
  },
```

To start the debugging, 
* switch to the debugger tab, 
* use the "Attach to Main.js" configuration
* start the debugger
* in the command line run "npm run start:debug"

You should get to the breakpoint - check the error you get.

**Comment by venkateshpenchala** [comment]
I Confirm the error "Failed to discover URL for service identified by Mobile.ImsStsAuth".

I debugged the code and here is what I got at the breakpoint.

![breakpoint](https://user-images.githubusercontent.com/15332516/50954023-7d940700-14b5-11e9-8611-cb385a962793.png)


If it helps, below is the debug trace from the terminal window:

 `Debugger listening on ws://127.0.0.1:38926/506d3b1b-465b-4928-b754-fe798ce4f4cb
For help see https://nodejs.org/en/docs/inspector
Debugger attached.


  QueryAgent
Trace   |imodel-query-agent| Geting JWT access token
Trace   |imodel-query-agent| Got JWT access token
Trace   |imodel-query-agent| Attempting to find Ids for iModel and Project
Trace   |imodel-query-agent| Project sample-agent has id: FAKE_WSG_ID
Trace   |imodel-query-agent| Query Agent Initialized with event subscriptions for sample-agent
Trace   |imodel-query-agent| Setting up changeset and named version listeners...
Trace   |imodel-query-agent| Listening to changesets for 10 ms.
Trace   |imodel-query-agent| Finished listening for changesets for 10 ms.
Trace   |imodel-query-agent| Setting up changeset and named version listeners...
Trace   |imodel-query-agent| Listening to changesets for 10 ms.
Trace   |imodel-query-agent| Finished listening for changesets for 10 ms.
    √ Extracts changeset information published to an iModel (119ms)
Trace   |imodel-query-agent| Geting JWT access token
Error   |imodel-query-agent| Unable to verify IModel: sample-agent', for project sample-agent' exists in the iModel Hub: Error: Mock login failure
    √ Throws error when async initialization fails

  QueryAgentConfig
    √ Uses __dirname/output as default output directory

  QueryAgentWebServer
Trace   |imodel-query-agent| Geting JWT access token
Trace   |imodel-query-agent| Got JWT access token
Trace   |imodel-query-agent| Attempting to find Ids for iModel and Project
Trace   |imodel-query-agent| Project sample-agent has id: FAKE_WSG_ID
Trace   |imodel-query-agent| Query Agent Initialized with event subscriptions for sample-agent
Trace   |imodel-query-agent| Setting up changeset and named version listeners...
Trace   |imodel-query-agent| Listening to changesets for 10 ms.
Trace   |imodel-query-agent| Finished listening for changesets for 10 ms.
    √ Extracts changeset information published to an iModel
Trace   |imodel-query-agent| Geting JWT access token
Error   |imodel-query-agent| Unable to verify IModel:' sample-agent', for project ' sample-agent' exists in the iModel Hub: Error: Mock login failure
    √ Returns false when listen for changesets routine throws error
Trace   |imodel-query-agent| Cleaning up test resources, may take some time...

  Main
Trace   |imodel-query-agent| Query Agent Web Server finished executing unsuccessfully.
    √ runs the Query Agent Web Server and handles process when invoked
Trace   |imodel-query-agent| Query Agent Web Server finished executing unsuccessfully.
    √ Catches error thrown when running Query Agent Web Server
Trace   |imodel-query-agent| Query Agent Web Server finished executing unsuccessfully.
    √ Executes properly when run result is false

  ChangeSummaryExtractor
Error   |imodel-query-agent| Error while extracting changeset summary FAKE_CHANGESET_ID: Bad Arg: iModel to extract change summaries for must be open and must not be a standalone iModel. {"ActivityId":"de5873c7-1d74-4f4b-aece-88768473168e"}
    √ Catches errors in its method

  IModelQueryAgentWebServer (#integration)
iModel Query Agent listening on http://localhost:3000
    √ Web server responds to '/' and '/ping'
Trace   |imodel-query-agent| Geting JWT access token {"ActivityId":"de5873c7-1d74-4f4b-aece-88768473168e"}
Error   |imodeljs-clients.Request| undefined ECONNABORTED: Timeout of 10000ms exceeded
Error   |imodel-query-agent| Unable to verify IModel:' sample-agent', for project ' sample-agent' exists in the iModel Hub: Failed to discover URL for service identified by "Mobile.ImsStsAuth"
    1) Extracts changeset information published to an iModel

  Main (#integration)
Trace   |imodel-query-agent| Geting JWT access token
iModel Query Agent listening on http://localhost:3000
PS D:\practise\iModel\imodel-query-agent-master>
`

**Comment by ramanujam-raman-zz** [comment]
Do you know if you have a system proxy setup? Can you try the following curl command - 
curl -G "https://buddi.bentley.com/WebService/GetUrl/?url=Mobile.ImsStsAuth&region=0"

You can download curl from - https://curl.haxx.se/download.html

**Comment by venkateshpenchala** [comment]
![curl](https://user-images.githubusercontent.com/15332516/51101718-1d1a0800-17dc-11e9-9099-5cf66c379748.png)
This is the output from Curl. Yes, I am behind a corporate proxy which is being configured.

**Comment by ramanujam-raman-zz** [comment]
We released a new version (iModel.js: 0.187.0, iModelQueryAgent) that may help either fix your issue, or at least diagnose it further. 

Upgrade to the latest version of imodel-query-agent, and set the environment HTTPS_PROXY to point to your proxy server before executing the application. 
```e.g., set HTTPS_PROXY=https://myproxy.com:2345```

If you still cannot get it to work, please start a fiddler trace trace before executing the application. Instructions below:

1. Install the fiddler app from http://www.telerik.com/fiddler
2. Unset HTTPS_PROXY env if it was setup earlier. 
3. Enable HTTPS calls to be captured and decrypted. 
    ```Tools -> Options -> Turn on "Capture HTTPS CONNECTs" and "Decrypt HTTPS traffic". ```
4. Start capturing the HTTPS traffic with 
    ```File -> Capture Traffic```
5. Reproduce the issue with imodel query agent. 
6. Save the captured trace and send it over. 
    ```File -> Save -> All Sessions```

**Comment by calebmshafer** [comment]
Due to inactivity this GitHub issue will be closed.  If the problem persists please re-open this issue or file a new one.
